name: Deploy to GoDaddy

on:
  push:
    branches: [ "main" ]   # runs every time you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: "./"
          remote_path: ${{ secrets.SFTP_TARGET }}
          sftp_only: true
          delete_remote_files: false
          # If you ever see "Host key verification failed", uncomment:
          # ssh_cmd_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

